### ISSUE TITLE
HYPHA - Right-Click Context Crashing Rack

### ISSUE THREAD

**Issue by McGroggin** [patheros/PathSetXOmriCohen#1]
Rack is consistently crashing hard when accessing the right click context menu in the HYPHA module. 

Hovering the mouse cursor over the entry 'Exclude Connected Outputs' seems to be the trigger, as I am able to access entries above that one without incident. As soon as the mouse cursor passes over the text for that entry however, Rack crashes with the following log entry:

[20.935 fatal adapters/standalone.cpp:49 fatalSignalHandler] Fatal signal 22. Stack trace:
22:  0x0
21: raise 0x7ffa0effabe0
20: abort 0x7ffa0efff1e0
19: ZN9DirSwitchD1Ev 0x7ff99e020920
18: ZN10MiniHyphaeD1Ev 0x7ff99e00d810
17: ZSt16__do_uninit_copyIPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPS5_ET0_T_SA_S9_ 0x7ff99e07ba80
16: ZZN4rack17createSubmenuItemINS_2ui8MenuItemEEEPS2_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_St8functionIFvPNS1_4MenuEEEbEN4ItemD1Ev 0x7ff99e0807a0
15: ZZN4rack17createSubmenuItemINS_2ui8MenuItemEEEPS2_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_St8functionIFvPNS1_4MenuEEEbEN4ItemD1Ev 0x7ff99e0807a0
14: ZNSt6vectorIiSaIiEE17_M_realloc_insertIJiEEEvN9__gnu_cxx17__normal_iteratorIPiS1_EEDpOT_ 0x7ff99e0713b0
13: ZNSt6vectorIiSaIiEE17_M_realloc_insertIJiEEEvN9__gnu_cxx17__normal_iteratorIPiS1_EEDpOT_ 0x7ff99e0713b0
12: ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_ 0x7ff99e07ebf0
11: ZNSt17_Function_handlerIFvPN4rack2ui4MenuEEZN16BaseHyphaeWidgetILi2ELi3ELi25ELi17ELi14ELi20ELi4ELi0ELi1EE17appendContextMenuES3_EUlS3_E0_E9_M_invokeERKSt9_Any_dataOS3_ 0x7ff99e06a850
10: ZZN4rack17createSubmenuItemINS_2ui8MenuItemEEEPS2_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_St8functionIFvPNS1_4MenuEEEbEN4Item15createChildMenuEv 0x7ff99e0806a0
9: ZN4rack2ui8MenuItem7onEnterERKNS_6widget6Widget10EnterEventE 0x7ff9aa3350e0
8: ZN4rack6widget10EventState11handleHoverENS_4math3VecES3_ 0x7ff9aa33b730
7: ZN4rack6window6Window4stepEv 0x7ff9aa340700
6: ZN4rack6window6Window3runEv 0x7ff9aa341150
5: ZN4rack6window6Window3runEv 0x7ff9aa341150
4: ZN4rack6window6Window3runEv 0x7ff9aa341150
3: ZN4rack6window6Window3runEv 0x7ff9aa341150
2: ZN4rack6window6Window3runEv 0x7ff9aa341150
1: BaseThreadInitThunk 0x7ffa0f257600
0: RtlUserThreadStart 0x7ffa10fc2680

VCV Rack Pro 2.3.0
Windows 10

**Comment by patheros** [comment]
@McGroggin thanks for the clear bug report. I was able to reproduce this and fix it locally. I will submit a fix for this to the VCV library within the next day.

**Comment by patheros** [comment]
Version 2.0.1 is live and should fix this.
