### ISSUE TITLE
Remove short fade in at start of playback

### ISSUE THREAD

**Issue by patheros** [patheros/PathSetXOmriCohen#10]
Thank you, I solved the pitch problem by adjusting the sample rate, but other problems still exist, the sound head problem is: every time the sound head is played, the head sound has a short volume fade in.

_Originally posted by @283062766 in https://github.com/patheros/PathSetXOmriCohen/issues/8#issuecomment-1573096100_

**Comment by patheros** [comment]
So I was able to reproduce this issue using a pure sine wave sample. Here you can see the fade in clearly happening on the scope:
![image](https://github.com/patheros/PathSetXOmriCohen/assets/4230677/21259690-ec4c-4773-ac7b-2fae98212e28)

I believe what is happening is the tapper on the grain is showing through here. Each grain is tapered in and out using a [hanning window](https://en.wikipedia.org/wiki/Hann_function). But when the sample first starts playing, there are no grains already playing, so the tapper of the first grain is clearly noticeable.

Overall though I'm not sure this is a problem? This tapper prevents harsh clicks/pops.

**Comment by omricohenmusic** [comment]
I believe that since the granular engine is always on, it's just a matter of changing the parameters to get a different result. For example, in this case, lowering the grain size will get rid of the fade in. 


https://github.com/patheros/PathSetXOmriCohen/assets/51967995/52c030bd-d123-4b94-b51a-f6e7ec583161

**Comment by 283062766** [comment]
I tried it and it did, I was misled by the defaults, this doesn't seem to be the problem, thanks a lot for helping me！
