### ISSUE TITLE
Chorus like effect when pitch knob reset to 0

### ISSUE THREAD

**Issue by patheros** [patheros/PathSetXOmriCohen#11]
Thank you for your reply, now there is one last question, when the pitch knob value returns to the middle value after modulation, the sample tone will become a sound similar to the chorus effect, because I use my computer with an Apple M2 processor , I'm not sure if this is my problem, hope you can give it a try.

_Originally posted by @283062766 in https://github.com/patheros/PathSetXOmriCohen/issues/8#issuecomment-1573124097_

**Comment by patheros** [comment]
@283062766, 

So I see it happening in your video but I have not been able to reproduce it.

Does it happen for you every time?

It sounds like the knob isn't going all the way back to 0. Could you try manually entering 0 for the knob value and see if that fixes it?

**Comment by 283062766** [comment]
Yes I have this problem every time, turning the knob and entering the value is the same, well, I may have to be patient, thank you!

**Comment by patheros** [comment]
@283062766 can you send me the sample you are using along with the settings: sample rate and thread count?

**Comment by 283062766** [comment]
[panther cap4.zip](https://github.com/patheros/PathSetXOmriCohen/files/11636663/panther.cap4.zip)
I recorded a new video and included the samples, thank you!

**Comment by patheros** [comment]
@283062766 I think I have a fix for this. Would you be interested in testing it? I so can you send me an email at [contact@patheros.com](mailto:contact@patheros.com)?

**Comment by 283062766** [comment]
no problem i can try

**Comment by patheros** [comment]
Fixed in v2.0.2

**Comment by 283062766** [comment]
Problem solved Great! Thank you for your work!
