### ISSUE TITLE
TRUFFLES: Clear All Samples Only Clears Current Slot.

### ISSUE THREAD

**Issue by McGroggin** [patheros/PathSetXOmriCohen#12]
Both the 'Clear Sample' and 'Clear ALL Samples' appear to have the same function.

'Clear Sample' works as expected in clearing the sample only from the slot selected with the 'Sample' knob.

'Clear ALL Samples' also only clears the currently selected slot. All other slots containing recorded samples retain their contents. Each slot must be selected and cleared manually.

Issue experienced across multiple sessions in two patches with both live recorded and loaded samples.

Win 10
VCV Rack Pro 2.3.0
Plugins up to date at time of submission.

**Comment by patheros** [comment]
@McGroggin Thanks for submitting this. I was able to find and fix the bug. It should be fixed in the next build. If you'd like to help test the fix before the next build is released please email me at contact@perblue.com

**Comment by patheros** [comment]
Fixed in v2.0.2
