### ISSUE TITLE
Clicks from Hyphae pitch shifter

### ISSUE THREAD

**Issue by patheros** [patheros/PathSetXOmriCohen#2]
From: @omricohenmusic
> The pitch shifter in Hyphae is still producing quite a harsh click noise after recording into it.

**Comment by patheros** [comment]
@Omri, for me the clicking happens only when the fade in and out are both set to 0. Is this the case for you as well?

If so I think I know what happened. The fade in and out use to have a minimum above 0, but I lowered it to 0 when I added the seamless looping. If this is the case I can set the minimum back up for just the Pitch Shifter.

**Comment by omricohenmusic** [comment]
https://github.com/patheros/PathSetXOmriCohen/assets/51967995/0d2c9a03-ba90-4655-9c35-23f816003e66

Here's a video about it. You can see that even with fade in and out, there's still noise

**Comment by patheros** [comment]
Fixed in v2.0.2
