### ISSUE TITLE
Multi File Load

### ISSUE THREAD

**Issue by patheros** [patheros/PathSetXOmriCohen#24]
From Omri: Having the option to load the first 16 files in a folder to all 16 slots.

**Comment by patheros** [comment]
@omricohenmusic you can already do this by dragging multiple files onto the module from outside VCV Rack.

To make the load dialog support this I believe I would need a second button and menu item that lets you select a folder. Is that worth doing?

**Comment by omricohenmusic** [comment]
Drag and drop is perfect :) No need to add anything else.
