### ISSUE TITLE
Variable Segment Lengths

### ISSUE THREAD

**Issue by patheros** [patheros/PathSetXOmriCohen#26]
From Omri: Something people asked for is the ability to change the loop length. I'm not so sure if that's fitting for this module, but what do you think?

**Comment by patheros** [comment]
@omricohenmusic I don't have a strong feeling. If we were to do this, how would you imaging it working. A right click menu per section? Maybe there are just a few settings for length? Or would you want something fancier, or dynamic depending on the record length?

**Comment by omricohenmusic** [comment]
Yeah, as I said, this module is all about having fixed lengths, so I think this can stay as is.
