### ISSUE TITLE
Audio Inputs not Polyphonic

### ISSUE THREAD

**Issue by patheros** [patheros/PathSetXOmriCohen#3]
From @omricohenmusic

> The audio inputs on Hyphae and Hypha are not polyphonic

**Comment by patheros** [comment]
@omricohenmusic, Is summing the inputs the desired behavior here?

**Comment by omricohenmusic** [comment]
Yeah, just like on PantherCap and Truffles.

**Comment by patheros** [comment]
Fixed in v2.0.2
