### ISSUE TITLE
Clicks in PantherCap when changing Overlap

### ISSUE THREAD

**Issue by patheros** [patheros/PathSetXOmriCohen#4]
from @omricohenmusic:

> Changing overlap on PantherCap will create clicks

**Comment by patheros** [comment]
@Omri, I'm not hearing any obvious clicks with the three samples I tried. When the Overlap size is low its a very stutterery sound but not clicky.

**Comment by omricohenmusic** [comment]
Here's a video about that. It happens also with modulation. 

https://github.com/patheros/PathSetXOmriCohen/assets/51967995/248435fe-1f19-41a7-855b-077037a3bb30

**Comment by patheros** [comment]
I am not able to reproduce the issue :(

Here is my patch file and a recording of it working correctly.

Can you test the patch file and test:
1. Does it have any clicks when you first open it?
2. If you clear the sample and re-record, does it have any clicks?

[HyphaeClicks.zip](https://github.com/patheros/PathSetXOmriCohen/files/11630289/HyphaeClicks.zip)

**Comment by omricohenmusic** [comment]
I didn't get any clicks from the Overlap when opening the patch or when using your sample, but I did get clicks when recording a new sine wave after clearing the sample.

**Comment by omricohenmusic** [comment]
Yeah, sure. 48kHz \ 1 thread \ Windows 10

**Comment by patheros** [comment]
Fixed in v2.0.2
