### ISSUE TITLE
Make Gate Polyphonic on PantherCap

### ISSUE THREAD

**Issue by patheros** [patheros/PathSetXOmriCohen#5]
from @omricohenmusic

> Can the gate input on PantherCap be also polyphonic?

**Comment by omricohenmusic** [comment]
Sorry, my bad, I meant the Run input. When using polyphonic pitch, it will then be possible to use the Run input with the polyphonic gates.

**Comment by patheros** [comment]
Patheros — 05/26/2023 2:22 AM
For making Run polyphonic: the easy change would be to make it sum all the channels so any signal would trigger all the voices. The more complicated chance would be to make multiple play heads, one for each voice. The more complicated change will take some work.

Omri Cohen — 05/26/2023 2:54 AM
Oh ok... I thought that since it's already polyphonic via the pitch, it will not be so complicated to add the Run as well. Are there no multiple playheads already because of the pitch polyphony?
I think that I see what you mean. So yes, let's have the Run just sum all the channels, and then it's possible to get polyphony via the Mix control with an external envelope.
I think that's the best option, and it should work quite nicely.

**Comment by patheros** [comment]
I ended up making it so all 5 trigger inputs on Panther Cap sum their input, if a polyphonic cable is attached.

**Comment by patheros** [comment]
Fixed in v2.0.2
