### ISSUE TITLE
Some questions about panther cap in use

### ISSUE THREAD

**Issue by 283062766** [patheros/PathSetXOmriCohen#8]
Hello, first of all thank you for everything, I found a few problems when using panther. . . 1: Loaded samples do not play the original pitch correctly, they always sound higher than the original samples. 2; The audio head cannot be played correctly. 3: When the pitch knob is turned and then returned to the 0 position, the sound of the sample will change (it feels like a chorus effect is added). Finally, I hope that the filp option can be turned off when adding randomize.

**Comment by patheros** [comment]
@283062766 Thank you for your feedback! I need some more details though to help track your issues down.

For your 1st point, can you provide an example patch and the sample you used? You can zip them and upload them here on git hub.

For your 2nd point I do not understand what you mean.

For your 3rd point. Does this happen all the time? Does this happen with every same you try? If not, can you provide an example patch and the sample you used?

For your 4th point I made a separate issue #9. I'll check with Omri on his thoughts on it.

**Comment by 283062766** [comment]
[panther cap2.mp4.zip](https://github.com/patheros/PathSetXOmriCohen/files/11620410/panther.cap2.mp4.zip)

Thank you for your reply, I am not sure if it is my operation problem, I just did a very simple thing, I will demonstrate it through video...

**Comment by patheros** [comment]
Thank you for the video! My guess is the sample rate of the file you are loading is different than the sample rate you have VCV rack running at. I believe that would cause the sample to play faster and at a higher pitch.

You can adjust the sample rate that VCV is running at in the Engine menu at the top: 

![Image](https://github.com/patheros/PathSetXOmriCohen/assets/4230677/908ca7da-503d-48b0-bcc7-cb1dc8f8c181)


---

For your 2nd point, I am still not sure what you mean by:
> 2; The audio head cannot be played correctly.

**Comment by 283062766** [comment]
Thank you, I solved the pitch problem by adjusting the sample rate, but other problems still exist, the sound head problem is: every time the sound head is played, the head sound has a short volume fade in.

**Comment by patheros** [comment]
Thank you for that context. I created a separate issue #10 to track the details on that issue.

**Comment by 283062766** [comment]
Thank you for your reply, now there is one last question, when the pitch knob value returns to the middle value after modulation, the sample tone will become a sound similar to the chorus effect, because I use my computer with an Apple M2 processor , I'm not sure if this is my problem, hope you can give it a try.

**Comment by patheros** [comment]
Ah, I see that now in your video. I created a new issue just for that #11, to help keep things organized.

**Comment by patheros** [comment]
I am going to close this issue since everything is moved to other issues.
