### ISSUE TITLE
Disable Flip on Randomize

### ISSUE THREAD

**Issue by patheros** [patheros/PathSetXOmriCohen#9]
from @283062766 in #8 

> I hope that the filp option can be turned off when adding randomize.

**Comment by omricohenmusic** [comment]
Will it be possible to add a menu in the right-click menu with options for the random? We can have then all the controls to select from so Length, Start, Flip, Time, Pitch, Size, and Overlap. Then the user can select which one to randomize with the random feature. Would that be ok? They will have to follow the Amount and Slew, and also the quantization for pitch, though. What do you think?

**Comment by 283062766** [comment]
This is great! It's going to be more fun, very much looking forward to it. .

**Comment by patheros** [comment]
Fixed in v2.0.2

**Comment by 283062766** [comment]
Problem solved Great! Thank you for your work!
